### ISSUE TITLE
Setup inicial

### ISSUE THREAD

**Issue by dajuam** [NibiruOS/afip#1]
Hola, me bajé el proyecto para chusmearlo pero no me queda claro cómo setear los parámetros para conectarme con WSAA. ¿Se podría detallar un poco más esa configuración?

**Comment by lbrasseur** [comment]
Hola, qué tal? No hemos tenido tiempo de documentar mucho, jeje. Fijate en esta clase:

https://github.com/NibiruOS/afip/blob/master/src/test/java/ar/com/system/afip/wsaa/business/impl/BouncyCastleWsaaManagerTest.java

hay constantes al principio donde se colocan los parámetros.

Pero antes de poder ejecutarlo deberías generar el certificado (es uno de los datos que tenés que poner en uno de los parámetros).

La generación del certificado se puede hacer con OpenSSL, pero esta librería permite hacerlo internamente. Fijate en esta clase:

https://github.com/NibiruOS/afip/blob/master/src/main/java/ar/com/system/afip/wsaa/business/api/WsaaManager.java

O su implementacion

https://github.com/NibiruOS/afip/blob/master/src/main/java/ar/com/system/afip/wsaa/business/impl/BouncyCastleWsaaManager.java

El método  buildCertificateRequest genera un requerimiento de certificado equivalente al que te generaria open ssl. Pero con esto lo podes generar desde tu aplicación. 

Eso lo registras en afip, por la página y el certificado que te den lo guardas llamando al método .updateCertificate

**Comment by lainz** [comment]
Hola, me pasa lo mismo me resulta complicado crear los objetos para hacer el login y luego solicitar el CAE. Si bien lo hice anteriormente para javascript y pascal, acá mejor usar esta solución que se ve muy completa, pero me haria falta un ejemplo muy simple donde se hace login y se envia una solicitud de CAE, al menos en homologacion.

Ya tengo el key y crt para poder usarlos, no necesito generarlos, con eso bastaba en las otras implementaciones.

Saludos.

**Comment by lbrasseur** [comment]
Hola, qué tal? veo que los links que puse antes ya no funcionan porque cambiaron los paquetes, jaja.

Agregamos algo de documentación en la Wiki: https://github.com/NibiruOS/afip/wiki

También agregamos una sección de inicio rápido: https://github.com/NibiruOS/afip/wiki/quickstart donde se muestra cómo ejecutar los tests unitarios. También hay un link a una app de ejemplo en Android.

Si querés ver mejor cómo está pensado, fijate la documentación en la sección de arquitectura: https://github.com/NibiruOS/afip/wiki/architecture . A lo mejor es un poco complejo, pero lo que pasa es que apuntamos a hacerlo lo más modular posible (para que se pueda integrar en diferentes productos)

Si ya tenés las keys y el crt generados, no hay problema, podés usarlos. Probablemente tengas que hacer una implementación de `WsaaDao` que las lea desde donde las tengas guardadas (filesystem, base de datos o lo que sea)

Fijate si viendo eso podés encaminarlo, si no, avisame y te doy una mano.

Saludos!

Lautaro

**Comment by lainz** [comment]
Hola, ok gracias. Estoy viendo desde los test, me baje el repo y empece a copiar algunos archivos java de los test asi puedo empezar, despues te cuento. La instalacion en android studio sin problemas, pero se ve que claro, la carpeta tests no viene si se instala o al menos android studio no encuentra esos archivos, por eso baje el repo.

Saludos.

**Comment by lbrasseur** [comment]
Ah, desde Android Studio podés clonar este proyecto e importarlo como proyecto Gradle (debería funcionar). Si no, capaz podés probar con [IntelliJ](https://www.jetbrains.com/idea/). En ambos casos te debería reconocer la carpeta `test` como código fuente y deberías poder ejecutarlo.

Si no, otra opción podría ser editar los archivos con cualquier editor de texto y ejecutar los tests directamente desde la línea de comando, con [Gradle](https://gradle.org/).

**Comment by lainz** [comment]
Ok gracias. Igual de todas formas no la puedo usar a la libreria, se ve que tiene bastantes dependencias y se me queda sin espacio el archivo dex (mi target de api es 17 y no lo puedo cambiar, probe con las distintas soluciones al tema del limite de 64 k metodos en archivo dex pero no me funciono, La app en si es pequeña no tiene tantos metodos).

**Comment by lbrasseur** [comment]
Probaste la Multidex Support Library? En teoría debería poder usarse para versiones previas a la 21

**Comment by lainz** [comment]
Hola, ayer lo habia probado pero no me funcionaba, hoy probe de nuevo y funciona, asi que espero poder usar la librería.

**Comment by lbrasseur** [comment]
Buenísimo,  avisa cualquier cosa

**Comment by lainz** [comment]
Hola, me funciona, probe traer el ultimo comprobante autorizado y esta correcto.

```Kotlin
Utils.initWsfe()
val ultimoAutorizado = WsfeComponents.wsfeManager().feCompUltimoAutorizado(2, 11)
```

Hay forma de poder hacer el login sin el DN/CN? Lo tengo funcionando en otro sistema y no requiere los parametros source y destination, funciona igual (lo que esta entre llaves esta comentado):

```Pascal
function _GenerarLoginTicketRequest(Source, destination, uniqueid,
  generationtime, expirationtime: string): string;
begin
  Result :=
    '<?xml version="1.0" encoding="UTF­8"?>' + LineEnding +
    '<loginTicketRequest version="1.0">' + LineEnding + '<header>' +
    LineEnding + {'  <source>' + Source + '</source>' + LineEnding +
    '  <destination>' + destination + '</destination>' + LineEnding +}
    '  <uniqueId>' + uniqueid + '</uniqueId>' + LineEnding +
    '  <generationTime>' + generationtime + '</generationTime>' +
    LineEnding + '  <expirationTime>' + expirationtime + '</expirationTime>' +
    LineEnding + '</header>' + LineEnding + '<service>wsfe</service>' +
    LineEnding + '</loginTicketRequest>';
end;
``` 

Me refiero a poder hacerlo sin tener que modificar el codigo de ustedes. Saludos.

**Comment by lbrasseur** [comment]
No sabía que eran opcionales, no consideramos la posiblidad de no incluirlos en el XML. En principio supongo que sí, habría que modificar código para eso.

Tal vez se podría probar poner un valor nulo. Veo que en esta clase:

https://github.com/NibiruOS/afip/blob/master/ar.com.system.afip/src/main/java/ar/com/system/afip/wsaa/business/impl/Header.java

permitimos nulos, pero al momento de crear el ticket request:

https://github.com/NibiruOS/afip/blob/master/ar.com.system.afip/src/main/java/ar/com/system/afip/wsaa/business/impl/LoginTicketRequest.java (método create)

le estamos pasando el source que se recibe y estamos creando el destination usando el environment.

El ticket es creado en el metodo login de esta clase:

https://github.com/NibiruOS/afip/blob/master/ar.com.system.afip/src/main/java/ar/com/system/afip/wsaa/business/impl/BouncyCastleWsaaManager.java

```
            String cms = LoginTicketRequest
                    .create(companyInfo.loginSource(),
                            service,
                            setupDao.readSetup()
                                    .getEnvironment())
                    .toXml(xmlConverter)
                    .toCms(certificate, privKey)
                    .toString();
```
A lo mejor se podría, para probar, retornar null en companyInfo.loginSource(), sólo para ver si el tag de XML es omitido.
 
(por curiosidad nomás, para qué necesitas omitir esos campos?)

**Comment by lainz** [comment]
Basicamente no lo almacenamos en nuestra BD, entonces no lo tenemos en cuenta. Ya que no lo tenemos en la BD ahorramos un paso al usuario de ingresar ese valor, pero nada mas. De otra forma deberiamos incluirlo en un campo mas en nuestro sitio de configuracion.
Tenemos funcionando tanto en la web como en escritorio y funciona ok sin ese valor, mas que nada por eso.

**Comment by lbrasseur** [comment]
Ahh, bueno, cuando tenga un rato armo un cambio para hacerlo opcional. O si querés proponer un pull request, dale para adelante nomás.

**Comment by lainz** [comment]
Ok gracias, mejor espero ya que no tengo mucha experiencia con Java, soy nuevo en esto de Android tambien y estoy usando Kotlin.

**Comment by lainz** [comment]
Muchas gracias ya tengo todo funcionando, la verdad me ahorraron mucho trabajo con este componente. Ya pude obtener el CAE y fecha de vencimiento. =)

**Comment by lbrasseur** [comment]
De nada! :)
