### ISSUE TITLE
CAEA: falta un campo requerido

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#10]
Hola buen día, quiero informar CAEA con la librería y me da este error:
`<Msg>El campo CbteFchHsGen es obligatorio informarlo cuando el punto de venta es del tipo CONTINGENCIA CAEA</Msg>`

Yo lo tengo andando en otro lenguaje (Pascal) y el campo es sencillo, es un string con el formato yyyyMMddHHmmss.

Es fácil de agregar un nuevo campo? Porque lo necesito, yo lo puedo probar si lo agregan, ya mas o menos se como compilar la librería sino miro de nuevo donde me explicaron como compilarla.

```
// ToDo: falta este campo
//inData.feCAEARegInfReq.feDetReq.fecaeaDetRequest[0].cbteFchHsGen = sFECHA
```

El archivo es FEDetRequest.class, yo estoy usando Kotlin en Android Studio.

**Comment by igentiletti** [comment]
Subí el agregado del campo en, en el branch develop, no pude probarlo, si podes, probarlo y comentarnos como anduvo.

**Comment by lainz** [comment]
Dale ahora en un rato lo pruebo y les digo. Muchas gracias.

**Comment by igentiletti** [comment]
Perdón, agregue el campo para el servicio wsmtxca, ahí te ajuste para wsfev1

**Comment by lainz** [comment]
Ah buenisimo, ahi estoy por bajar todo y compilar.

**Comment by lainz** [comment]
Anduvo perfecto, mil gracias.

`<Resultado>A</Resultado>`
