### ISSUE TITLE
Error al informar Nota de Crédito

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#12]
Hola, el campo CbteFch no es obligatorio, lo tengo andando en otro sistema sin pasar ese campo

`W/System.err: java.lang.RuntimeException: org.simpleframework.xml.core.ElementException: Value for @org.simpleframework.xml.Element(data=false, name=CbteFch, required=true, type=void) on field 'cbteFch' protected java.lang.String ar.com.system.afip.wsfe.service.api.CbteAsoc.cbteFch is null in class ar.com.system.afip.wsfe.service.api.CbteAsoc`

A la tarde voy a probar de la misma forma que probé el tema del CAEA y les cuento.

**Comment by lainz** [comment]
```
@XmlElement(name = "CbteFch")
    @Element(name = "CbteFch", required = false)
    protected String cbteFch;
```
Agregando el required = false, me anduvo bien.

**Comment by lbrasseur** [comment]
Hola, qué tal? Perdón por la demora, no he tenido tiempo de ver esto.

Buenísimo, podés crear un pull request para esto? Gracias!

**Comment by lbrasseur** [comment]
Mergeado!
