### ISSUE TITLE
javax.net.ssl.SSLException: Read error:  I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#13]
Hola buen día,

Tienen idea de que puede estar pasando cuando a un cliente le sale este error?

`javax.net.ssl.SSLException: Read error:  I/O error during system call, Connection reset by peer
`
Lamentablemente no me pasa en mi equipo y no tengo el stacktrace. Pero agregue firebase crashlytics para ver si lo puedo sacar.

Les paso alguna vez ese error con la librería? Porque no uso otra cosa de internet al facturar y le pasa al facturar / informar CAEA que es cuando uso esta librería. Tiene Android 6.0

Gracias.

**Comment by lbrasseur** [comment]
Hola, qué tal? Perdón por la demora, no he tenido tiempo de ver esto. No recuerdo que nos haya dado ese error, podrás conseguir el stack trace? Suena a que puede ser algo del lado del server.

**Comment by lbrasseur** [comment]
Este error sigue ocurriendo?

**Comment by lainz** [comment]
Es un error con mala conexión de internet, es de la librería que usan para hacer la conexión, pero no pasó de nuevo, el cliente cambio si no me equivoco el wifi por una tarjeta sim y con eso anduvo.

**Comment by lbrasseur** [comment]
Ahh, entonces debe haber sido por algún problema de conectividad. No estamos controlando ese tipo de errores en la librería, deberían hacerse por afuera de la misma :(
