### ISSUE TITLE
Error en unit tests

### ISSUE THREAD

**Issue by lbrasseur** [NibiruOS/afip#15]
Poniendo así, required = false, anda bien:

```
@Element(name = "Iva", required = false)
    protected ArrayOfAlicIva iva;
```

Lo unico eso falla los tests, y ahi no tengo idea como cambiarlos.. Pero ya me funciona, podrían agregar ese cambio? Gracias.

_Originally posted by @lainz in https://github.com/NibiruOS/afip/issues/11#issuecomment-762842955_

**Comment by lbrasseur** [comment]
@lainz qué error te dan los tests? En teoría no debería afectar el hecho de hacer que unos campos sean opcionales (sólo en teoría, jaja).

**Comment by lainz** [comment]
Hola la verdad no tengo idea. Se que no me compilaba nomas no me acuerdo
como hice...

**Comment by lainz** [comment]
Este bug cerralo nomas, si no les da problemas a ustedes al distribuir la librería no pasa nada.

**Comment by lbrasseur** [comment]
Dale, perdón por la demora. Gracias!
