### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#17]
Hola, buscando timeout encontré esto:

```
    @Override
    public Retrofit.Builder get() {
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);

        return new Retrofit.Builder()
                .client(new OkHttpClient.Builder()
                        .addInterceptor(logging)
                        .addInterceptor(new FaultCodeInterceptor())
                        .readTimeout(1, TimeUnit.MINUTES)
                        .build())
                .addConverterFactory(RetroSoapFactory
                        .create(SimpleXmlConverterFactory.create(new Persister(new AnnotationStrategy())),
                                serializerProvider,
                                pullParserProvider,
                                SoapSpec.V_1_1));
    }
```

Pero no se si tiene que ver con el problema que estamos teniendo. Nosotros al no recibir CAE de AFIP guardamos como CAEA, pero un cliente tiene las ventas duplicadas con CAE y CAEA. Pensamos que quizás es un error de timeout, que afip crea el CAE pero no llegamos a recibirlo por algún error de conexión, guardamos como CAEA y ahi se duplica.

Les pasó algo así? Como solucionarlo?

**Comment by lbrasseur** [comment]
Perdón, no había visto esto. Sí, podes probar ponerle  más de 1 minuto de timeout para probar si ese es el problema.
