### ISSUE TITLE
Android 12: no such algorithm SHA512WITHRSA

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#18]
En nuestro programa no deja hacer CAE porque dice org.bouncycastle que no encuentra el algoritmo. Es Android 12. Hay alguna manera de solventarlo?

**Comment by lainz** [comment]
Lo probé con el emulador y esto es lo que sale en la consola:

```
W/System.err: java.lang.RuntimeException: org.bouncycastle.operator.OperatorCreationException: cannot create signer: no such algorithm: SHA512WITHRSA for provider BC
W/System.err:     at com.google.common.base.Throwables.propagate(Throwables.java:241)
W/System.err:     at ar.com.system.afip.wsaa.business.impl.LoginTicketRequest$Xml$Cms.toString(LoginTicketRequest.java:120)
W/System.err:     at ar.com.system.afip.wsaa.business.impl.BouncyCastleWsaaManager.login(BouncyCastleWsaaManager.java:169)
W/System.err:     at ar.com.system.afip.wsaa.business.impl.WsaaTemplateImpl.login(WsaaTemplateImpl.java:77)
W/System.err:     at ar.com.system.afip.wsaa.business.impl.WsaaTemplateImpl.runAuhtenticated(WsaaTemplateImpl.java:54)
W/System.err:     at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.feCompUltimoAutorizado(WsfeManagerImpl.java:59)
W/System.err:     at com.arandusoft.posberry.ventas.VentaViewModel.facturaElectronica(VentaViewModel.kt:2669)
W/System.err:     at com.arandusoft.posberry.ventas.VentaViewModel.prepararVenta(VentaViewModel.kt:1504)
W/System.err:     at com.arandusoft.posberry.ventas.VentaViewModel.prepararVenta$default(VentaViewModel.kt:1279)
W/System.err:     at com.arandusoft.posberry.ventastablet.CobrarActivity$prepararVenta$1.invokeSuspend(CobrarActivity.kt:380)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
W/System.err: Caused by: org.bouncycastle.operator.OperatorCreationException: cannot create signer: no such algorithm: SHA512WITHRSA for provider BC
W/System.err:     at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source:53)
W/System.err:     at ar.com.system.afip.wsaa.business.impl.LoginTicketRequest$Xml$Cms.toSignedData(LoginTicketRequest.java:143)
W/System.err:     at ar.com.system.afip.wsaa.business.impl.LoginTicketRequest$Xml$Cms.toString(LoginTicketRequest.java:115)
W/System.err: 	... 14 more
W/System.err: Caused by: java.security.NoSuchAlgorithmException: no such algorithm: SHA512WITHRSA for provider BC
W/System.err:     at sun.security.jca.GetInstance.getService(GetInstance.java:87)
W/System.err:     at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
W/System.err:     at java.security.Signature.getInstance(Signature.java:504)
W/System.err:     at org.bouncycastle.jcajce.util.NamedJcaJceHelper.createSignature(Unknown Source:2)
W/System.err:     at org.bouncycastle.operator.jcajce.OperatorHelper.createSignature(Unknown Source:36)
W/System.err:     at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source:4)
W/System.err: 	... 16 more
```

**Comment by lainz** [comment]
Acá encontré algo de documentación
https://developer.android.com/about/versions/12/behavior-changes-all#bouncy-castle

Android 12 quita muchas implementaciones de [BouncyCastle](https://www.bouncycastle.org/) de algoritmos criptográficos que anteriormente estaban obsoletos, incluidos todos los algoritmos AES. En cambio, el sistema usa las implementaciones de [Conscrypt](https://github.com/google/conscrypt) de esos algoritmos.

**Comment by lainz** [comment]
Este cambio afecta a la app si se cumple alguna de las siguientes condiciones:

La app usa tamaños de claves de 512 bits. Conscrypt no admite este tamaño. Si es necesario, actualiza la lógica criptográfica de la app para usar diferentes tamaños de claves.
La app usa tamaños de claves no válidos con KeyGenerator. La implementación de [KeyGenerator](https://developer.android.com/reference/javax/crypto/KeyGenerator) de Conscrypt realiza una validación adicional de los parámetros clave, en comparación con BouncyCastle. Por ejemplo, Conscrypt no permite que la app genere una clave AES de 64 bits, ya que AES solo es compatible con claves de 128, 192 y 256 bits.

Bouncy Castle permite generar claves de tamaños no válidos, pero luego falla si estas se usan con [Cipher](https://developer.android.com/reference/javax/crypto/Cipher). Conscrypt falla antes.

Inicializa los algoritmos de cifrado en modo Galois/Counter (GCM) con un tamaño diferente a 12 bytes. La implementación de [GcmParameterSpec](https://developer.android.com/reference/javax/crypto/spec/GCMParameterSpec) de Conscrypt requiere una inicialización de 12 bytes, que NIST recomienda.

**Comment by lainz** [comment]
Creo que tiene que ver que se usa el algoritmo de 512, se podrá cambiar a 256 para probar?

O usar la otra librería que se menciona, Conscrypt.

**Comment by lbrasseur** [comment]
Hola, qué tal? perdón por la demora y gracias por la investigación. Por lo que veo estamos usando SHA512withRSA  para firmar el login. (Está en la constante `ar.com.system.afip.wsaa.business.impl.BouncyCastleWsaaManager.SIGNING_ALGORITHM`).

Se podría cambiar esa constante para. probar, pero probablemente sea un requerimiento de AFIP. Si Android 12 no lo soporta.

Por lo que comentás Conscrypt tampoco lo soporta, por lo que habría que buscar otra opción.

Podés probar cambiando la constante? Solo para descartar, si eso funciona sería lo más simple.

**Comment by lainz** [comment]
Intento compilar con IntelliJ IDEA Community Edition, me compila solo la lib de ar.com.system.afip-1.3.0.jar, la jre y la android no me las esta compilando.

**Comment by lainz** [comment]
No se si es necesario compilar las 3 cosas como librerias por eso te pregunto. Y otra cosa que vi es que cambiaron en ese mismo archivo donde esta la encriptación, que ahora el nombre de la empresa, cuit y demás es requerido?

**Comment by lainz** [comment]
Hola alguna novedad con la encriptación en Android 12?

**Comment by lbrasseur** [comment]
Hola, qué tal? Perdón por la demora, no tengo un ambiente armado como para probar en Android. Dejame que consulto por el tema de la empresa y cuit.

**Comment by lbrasseur** [comment]
Qué error te da al compilar la librería para Android?

**Comment by lainz** [comment]
No da ningun error, simplemente no crea el archivo jar pero si los archivos class.

Por eso te pregunto si lo que puedo hacer es directamente copiar las carpetas a mi proyecto, y que despues las compile dentro del mismo proyecto.

**Comment by lbrasseur** [comment]
Ahh. los JARs deberían quedar en el directorio `build/lib` si no me equivoco, de cada proyecto.

IntelliJ usa Gradle (en este caso) para hacer el build. Lo que podrías probar es, desde el directorio del proyecto, ejecutar:
```
gradlew clean build
```
Y ver si genera las librerías en `build/lib`.
Si importaste el proyecto desde IntelliJ, probablemente haya generado los archivos `gradlew.bat` y `gradlew.sh` en el directorio raíz (ambos sirven para ejecutar Gradle, el primero desde Windows y el segundo desde Linux y similares).

**Comment by lainz** [comment]
Uso el click derecho > build en cada carpeta, y solo me aparece el lib/jar en el primero, en los otros dos no aparece.

Podrias hacer un mini tutorial de como compilar, al menos con el IDE que ustedes usen no tengo problema en bajar otro. De paso revisas si esta compilando los jar.

**Comment by lainz** [comment]
Hola, ya pude incluir la libreria en el proyecto sin usar los jar, copiando y pegando el codigo. Que algoritmo puedo usar para probar? Ya probe SHA256withRSA y me dice que tampoco lo encuentra...

Saludos.

**Comment by lbrasseur** [comment]
Hola, qué tal? Que raro que no te haya funcionado con los JARs, compilaste con la misma versión de Java?

El problema de cambiar el algoritmo de firmado es que seguramente no va a funcionar porque supongo que AFIP espera que sea `SHA512withRSA`. Igualmente habría que ver por qué no los reconoce (ni idea por qué).

Otra posibilidad podría ser probar cambiar la versión de BouncyCastle en el archivo [build.gradle](https://github.com/NibiruOS/afip/blob/master/ar.com.system.afip/build.gradle). Veo que estamos usando una versión para JDK 1.5, probablemente eso haya sido así para soportar versiones antiguas de Android. Veo [acá](https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on) que la última versión es `1.70`.  Veo que hay [otro](https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15to18) que dice `jdk15to18` en la versión.

¿Podés probar con alguno de esos? Gracias!!

**Comment by lainz** [comment]
Mira no tengo versiones de Java tan viejas, tengo las que vienen con Android Studio.

Lo que hice fue copiar las carpetas a mi proyecto de Android Studio, y en un principio usan una versión vieja de Room database. Lo demás compiló sin problemas.

El tema es que fueron cambiando la forma que se trabaja con la librería parece, y no supe bien como integrarla con los cambios nuevos. Asi que edite y harcodee algunos datos como el key y crt a ver si hacía login con otro algoritmo, pero no, no funciona.

Y el algoritmo no es que sea por la versión, sino que está deprecated...

**Comment by lainz** [comment]
Hola, le preguntamos a ChatGPT y dice que la solucion es poner SpongyCastle, que soluciona el problema con Android 11 y superiores.

Podrias modificar la libreria para que use SpongyCastle en Android? Y despues vemos de compilarla y adaptar los ultimos cambios que ustedes hicieron en nuestro proyecto.

Si podes contestar hoy te agradeceria =)

**Comment by lainz** [comment]
En su momento no te habia entendido lo de la version de bouncy castle, pense que era la version de java que me decias, ahi voy a probar con las versiones mas nuevas y te comento,. Sino como dije antes lo que recomienda ChatGPT es usar SpongyCastle.

**Comment by lainz** [comment]
Hola, probe con 'org.bouncycastle:bcpkix-jdk15to18:1.75' y da el error:

org.bouncycastle.operator.OperatorCreationException: cannot create signer: no such algorithm: SHA512WITHRSA for provider BC

**Comment by igentiletti** [comment]
Hola, qué tal? Disculpa la demora, estamos medio complicados con los tiempos. El fin de semana si te parece instalamos algún emulador de Android 11 y probamos migrar de BouncyCastle a SpongyCastle.

**Comment by lainz** [comment]
Dale, yo tambien tuve problemas al querer usar la ultima versión de la librería, se ve que cambiaron varias cosas y no la pude usar. Me decia que tenia que configurar el nombre de la empresa antes de hacer login, cuando con el codigo que ya tengo version 1.1.2 no es necesario.

**Comment by lainz** [comment]
Lo arreglamos por otro lado. Gracias de todas formas.
