### ISSUE TITLE
Redondeo decimales

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#3]
Hola, les dejo este tip por si les llega a pasar lo mismo que a mi.

Al cargar los valores en feDetReq.fecaeDetRequest[0].impTotal y en los demas campos de IVA, tambien en las alicuotas de IVA, AFIP requiere un formato especifico de decimales, sino devuelve un error. Como los Double en Java o Kotlin tienen mucha precision, termina teniendo mas decimales que los que AFIP permite.

Para solucionarlo en Kotlin pueden agregar esta funcion a su unidad de factura electrónica o unidad de utilidades:

```Kotlin
fun Double.round(decimals: Int): Double {
    var multiplier = 1.0
    repeat(decimals) { multiplier *= 10 }
    return round(this * multiplier) / multiplier
}
```

Y redondear a dos decimales o los que necesiten

```Kotlin
feDetReq.fecaeDetRequest[0].impTotal = impTotal.round(2)
```

**Comment by lbrasseur** [comment]
El problema es cuando llama al servicio SOAP? serializa el monto con varios decimales por la pérdida de precisión del double? Si es así, probablemente convenga cambiar ese campo a BigDecimal. Pero habría que ver si los distintos mecanismos de serialzazión a XML (SimpleXML en Android, JAX-WS en JRE) lo soportan. Si mal no recuerdo, creo que SimpleXML no lo soporta (hay que escribir un serializador).

**Comment by lainz** [comment]
El problema claro es al llamar el servicio SOAP, lo que pasa es que AFIP tiene este formato
http://www.afip.gov.ar/fe/documentos/manual_desarrollador_COMPG_v2.pdf

No se si ese es exacto el PDF, pero lo mismo donde dice Double dice 13+2. Por ejemplo si el Double dice 10.282828282828 ahi se falla. Por supuesto esto cuando los valores se calculan con operaciones.

Me paso lo mismo en una app en Pascal, asi que ahi redondeo tambien a dos decimales.

**Comment by lainz** [comment]
Ahi en ese mismo PDF encontre que es 13 numeros para la parte entera y dos para los decimales

**Comment by lbrasseur** [comment]
Ah, buenisimo, pruebo armar un serializador que lo convierta a esa cantidad de decimales. Gracias!

**Comment by lainz** [comment]
Ok perfecto, igual mira que hay otros campos que tienen distinto formato, ahi estan en ese PDF de todas formas.

**Comment by lbrasseur** [comment]
Gracias

**Comment by lbrasseur** [comment]
Este error sigue ocurriendo?

**Comment by lainz** [comment]
Mira hasta ahora anda todo bien con la librería, la usa mucha gente así que esta todo ok.

**Comment by lbrasseur** [comment]
Buenísimo, cierro el issue entonces, muchas gracias!
