### ISSUE TITLE
Error en Android 9 y 10

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#4]
E/AFIP: org.bouncycastle.operator.OperatorCreationException: cannot create signer: The BC provider no longer provides an implementation for Signature.SHA512WITHRSA.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.

**Comment by lbrasseur** [comment]
Cuando tenga un rato lo reviso. Gracias!

**Comment by lbrasseur** [comment]
Este error sigue ocurriendo?

**Comment by lainz** [comment]
Hola, lo venimos usando todo bien por ahora.

**Comment by lbrasseur** [comment]
Buenísimo, cierro el issue entonces. Gracias!
