### ISSUE TITLE
DN/CN opcional

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#5]
Hola, alguna novedad con respecto a hacer opcional este campo?

Lo habiamos charlado en este issue:
https://github.com/NibiruOS/afip/issues/1#issuecomment-546500833

**Comment by lbrasseur** [comment]
Hola, qué tal? Lo armo en un branch, lo probás ahi y si funciona lo mergeamos, te parece?

**Comment by lainz** [comment]
Hola, si muchas gracias.

**Comment by lbrasseur** [comment]
Subi cambios en este branch:

https://github.com/NibiruOS/afip/tree/feature/source_destination_opcional

Acá podes ver los cambios:

https://github.com/NibiruOS/afip/compare/develop...feature/source_destination_opcional

Basicamente lo que se me ocurrió es hacer que en el objeto Setup el environment sea opcional (se usa solo para crear el destination en el login).

Todavía no lo probé porque perdí mis keys de AFIP, capaz puedo generar unas nuevas.

Para probarlo vos, deberías clonarte ese branch e instalarlo en el repo Maven local mediante:

`gradle install`
o
`gradlew install`

Desde tu aplicación, actualizá la versión (fijate que la cambié a `1.1.2-SNAPSHOT`, cuando terminemos de cerrar los bugs la cerramos en `1.1.2`)

También tendrías que hacer una implementación de `SetupDao` que setee `null` en el environment, por ejemplo:

```
public class MiHomoSetupDao extends BaseSetupDao {
	public HomoSetupDao(Service billingService) {
		super(billingService);
	}

	@Override
	public Setup readSetup() {
		return new Setup(
				"https://wsaahomo.afip.gov.ar/ws/services/LoginCms?wsdl",
				"https://wsaahomo.afip.gov.ar/ws/services/LoginCms",
				billingService.getHomoWsdl(),
				null);  // Aca es donde se le pasa nulo
	}
}
```

**Comment by lbrasseur** [comment]
Lo acabo de probar con las clases de Android y aparentemente funciona. Me habia faltado un ajuste menor en la clase Header nomás.

**Comment by lainz** [comment]
Ok buenisimo, voy a ver si lo puedo probar en la semana justo estoy haciendo los ultimos cambios en esa app de android asi que me viene perfecto estos cambios, tengo el codigo en el trabajo, no se bien cuando pueda probarlo ya que me quedan aun cosas por terminar pero veo le demos prioridad asi ya podes subir tranquilo que funciona.

**Comment by lbrasseur** [comment]
Buenisimo, gracias! Estuve medio complicado de tiempos, por eso recién lo pude ver hoy a todo esto.

**Comment by lainz** [comment]
Si te entiendo perfecto yo tambien hago algunas librerias para Pascal, y a veces no tengo tiempo tampoco.

**Comment by lainz** [comment]
Hola, disculpa recien hoy termine de hacer otras cosas y puedo probar el tema del DN.

Cambie como me habias dicho en la aplicación la versión a 1.1.2-SNAPSHOT para poder probar, pero me dice que no la encuentra.

Tengo que copiar las carpetas a mi proyecto de android studio?

**Comment by lbrasseur** [comment]
Hola, qué tal? Deberías instalar el JAR localmente. Para esto, tenés que clonar el repo, ir al branch `develop` y ejecutar:

`gradle install`

Si no tenes Gradle instalado, lo que podés hacer es importar el proyecto desde IntelliJ o Android Studio para que te configure el Gradle Wrapper. De esta manera te genera un archivo `gradlew` y uno `gradlew.bat` (para Linux o Windows) en el directorio del proyecto con el que podrías ejecutar:

`gradlew.bat install`

**Comment by lainz** [comment]
Hola, ok pruebo y te cuento. Gracias.

**Comment by lainz** [comment]
Lo abri en IntelliJ, me sale este error:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\Damian\Documents\GitHub\afip\build.gradle' line: 88
> 
> * What went wrong:
> A problem occurred evaluating root project 'afip'.
> > Could not get unknown property 'sonatypeUser' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 25s

**Comment by lainz** [comment]
Será que tengo que registrarme en maven y poner mi usuario ahi? O en sonatype?

**Comment by lbrasseur** [comment]
Perdón,  me olvidé de ese tema. Gradle está intentando leer el usuario y clave que uso para publicar a Sonatype. Pero como no vas a publicar, lo podes dejar vacío. 

Para esto, crea un archivo gradle.properties en tu home directory, con ambos valores vacíos :

```
sonatypeUser=
sonatypePassword=
```
Acá hay un poco de documentación sobre ese archivo:


https://docs.gradle.org/current/userguide/build_environment.html

https://www.labkey.org/Documentation/wiki-page.view?name=gradleProps

**Comment by lainz** [comment]
Bien, pude compilar, ahora puse los .jar en mi carpeta libs y me los detecto sin problemas.

Ahora sigue la parte de crear MiHomoSetupDao para pasarle el ultimo parametro en null, el tema es que me da este error al hacer mi propia clase:

![error_afip](https://user-images.githubusercontent.com/4131395/70095014-795b6580-1602-11ea-836a-c1ac87b9f773.png)

BaseSetupDao no es publico y no se puede acceder para hacer el extends.

**Comment by lbrasseur** [comment]
Es un error, se ve que nunca necesitamos extenderlo desde otro paquete. Si querés hacelo público y enviá un pull request. Si no,  lo arreglo yo mañana. Gracias por encontrar el error!

**Comment by lainz** [comment]
Ok dale, ahora pruebo y si anda todo ok mando el pull request.

**Comment by lainz** [comment]
Listo, funcionó perfecto. Muchisimas gracias!

**Comment by lbrasseur** [comment]
Buenísimo, gracias a vos! puse un comentario en el Pull Request
