### ISSUE TITLE
Error en producción WSFE

### ISSUE THREAD

**Issue by lainz** [NibiruOS/afip#8]
Hola, hay un tema que surgió y al parecer tiene que ver con la llave privada. En homologación tenemos una llave privada que empieza con:

> -----BEGIN RSA PRIVATE KEY-----

Y en producción tenemos una llave privada que empieza con:

> -----BEGIN PRIVATE KEY-----

Ambos nos funcionan en nuestro sistema que usa Lazarus Free Pascal en Windows, Linux y Mac, usando la librería OpenSSL.

Pero tengo un problema al intentar usar la llave privada en producción en Android con su librería:

> org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair

Me sale este error. Intenté varias cosas:

- A la llave privada sacarle lo que dice BEGIN PRIVATE KEY y END PRIVATE KEY con los guiones y el espacio. Me sale otro error (Attempt to invoke virtual method 'org.bouncycastle.asn1.pkcs.PrivateKeyInfo org.bouncycastle.openssl.PEMKeyPair.getPrivateKeyInfo()' on a null object reference)

- Probe cambiar BEGIN PRIVATE KEY con BEGIN RSA PRIVATE KEY. Me sale otro error (org.bouncycastle.openssl.PEMException: malformed sequence in RSA private key)

Mi pregunta es si funciona en el otro sistema por que aca no funciona, es por el tema del "RSA"? O es que no soporta llaves sin "RSA". O es otra cosa?

**Comment by lainz** [comment]
https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key

**Comment by lbrasseur** [comment]
Justo estaba mirando ese mismo link. Aparentemente son 2 formatos diferentes (PKCS#1 y PKCS#8). 

Dejame ver si hay alguna forma de convertirlo.

**Comment by lbrasseur** [comment]
Aparentemente con OpenSSL se puede hacer, eso sería una solución rápida:

https://gist.github.com/gtaban/410db2351e52ae36a2a636f3cc6f86ac

También hay una herramienta online, pero no sería muy seguro poner una clave en una página, jeje:

https://8gwifi.org/pemconvert.jsp


Por otro lado, debe ser posible abrir PKCS#8 con Bouncy Castle, lo voy a buscar

**Comment by lainz** [comment]
Ok gracias, si aca encontramos https://knowledge.digicert.com/solution/SO26630.html

**Comment by lainz** [comment]
Pero si, mejor si lo abre directo la libreria asi no hay que convertir, son muchos clientes

**Comment by esvignolo** [comment]
> Aparentemente con OpenSSL se puede hacer, eso sería una solución rápida:
> 
> https://gist.github.com/gtaban/410db2351e52ae36a2a636f3cc6f86ac
> 
> También hay una herramienta online, pero no sería muy seguro poner una clave en una página, jeje:
> 
> https://8gwifi.org/pemconvert.jsp
> 
> Por otro lado, debe ser posible abrir PKCS#8 con Bouncy Castle, lo voy a buscar

Hola! creo que debería ser convertir así:

To convert from PKCS#8 to PKCS#1:
openssl rsa -in key1.pem -out key2.pem

**Comment by esvignolo** [comment]
Puede ser?

https://stackoverrun.com/es/q/12273887

**Comment by lbrasseur** [comment]
> > Aparentemente con OpenSSL se puede hacer, eso sería una solución rápida:
> > https://gist.github.com/gtaban/410db2351e52ae36a2a636f3cc6f86ac
> > También hay una herramienta online, pero no sería muy seguro poner una clave en una página, jeje:
> > https://8gwifi.org/pemconvert.jsp
> > Por otro lado, debe ser posible abrir PKCS#8 con Bouncy Castle, lo voy a buscar
> 
> Hola! creo que debería ser convertir así:
> 
> To convert from PKCS#8 to PKCS#1:
> openssl rsa -in key1.pem -out key2.pem

Si, puede ser. 

Por lo que leo en la doc, el PEMParser deberia poder leer PKCS#8:

https://www.bouncycastle.org/docs/pkixdocs1.5on/org/bouncycastle/openssl/PEMParser.html

pero viendo algunos ejemplos, parece ser que este formato encripta el contenido y necesita una  password:

https://stackoverflow.com/questions/46767281/reading-pkcs8-in-pem-format-cannot-find-provider

Supongo que el error lo estamos teniendo aquí:

https://github.com/NibiruOS/afip/blob/master/ar.com.system.afip/src/main/java/ar/com/system/afip/wsaa/business/impl/BouncyCastleWsaaManager.java

en la línea 150:

```
            PEMKeyPair pemKeyPair = fromPem(companyInfo.getPrivateKey());
```
Capaz sería útil debugguear la app y ver qué se está retornando ahí.

**Comment by esvignolo** [comment]
> > > Aparentemente con OpenSSL se puede hacer, eso sería una solución rápida:
> > > https://gist.github.com/gtaban/410db2351e52ae36a2a636f3cc6f86ac
> > > También hay una herramienta online, pero no sería muy seguro poner una clave en una página, jeje:
> > > https://8gwifi.org/pemconvert.jsp
> > > Por otro lado, debe ser posible abrir PKCS#8 con Bouncy Castle, lo voy a buscar
> > 
> > 
> > Hola! creo que debería ser convertir así:
> > To convert from PKCS#8 to PKCS#1:
> > openssl rsa -in key1.pem -out key2.pem
> 
> Si, puede ser.
> 
> Por lo que leo en la doc, el PEMParser deberia poder leer PKCS#8:
> 
> https://www.bouncycastle.org/docs/pkixdocs1.5on/org/bouncycastle/openssl/PEMParser.html
> 
> pero viendo algunos ejemplos, parece ser que este formato encripta el contenido y necesita una password:
> 
> https://stackoverflow.com/questions/46767281/reading-pkcs8-in-pem-format-cannot-find-provider
> 
> Supongo que el error lo estamos teniendo aquí:
> 
> https://github.com/NibiruOS/afip/blob/master/ar.com.system.afip/src/main/java/ar/com/system/afip/wsaa/business/impl/BouncyCastleWsaaManager.java
> 
> en la línea 150:
> 
> ```
>             PEMKeyPair pemKeyPair = fromPem(companyInfo.getPrivateKey());
> ```
> 
> Capaz sería útil debugguear la app y ver qué se está retornando ahí.

Hola Lautaro, si existe un password en la generación del key, pero en la documentación de AFIP figura que debe ir vacío, con lo cual, no debería existir password.

Queres q hagamos alguna prueba?

**Comment by lbrasseur** [comment]
Tienen el stack trace con el error que ocurre? así intento reproducirlo mañana, generando una clave nueva.

**Comment by lainz** [comment]
> 2020-03-25 21:03:20.239 5029-6054/com.arandusoft.posberry E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
>     Process: com.arandusoft.posberry, PID: 5029
>     java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair
>         at ar.com.system.afip.wsaa.business.impl.BouncyCastleWsaaManager.login(BouncyCastleWsaaManager.java:154)
>         at ar.com.system.afip.wsaa.business.impl.WsaaTemplateImpl.login(WsaaTemplateImpl.java:77)
>         at ar.com.system.afip.wsaa.business.impl.WsaaTemplateImpl.runAuhtenticated(WsaaTemplateImpl.java:54)
>         at ar.com.system.afip.wsfe.business.impl.WsfeManagerImpl.feCompUltimoAutorizado(WsfeManagerImpl.java:59)
>         at com.arandusoft.posberry.ventas.VentaViewModel.facturaElectronica(VentaViewModel.kt:1325)
>         at com.arandusoft.posberry.ventas.VentaViewModel.prepararVenta(VentaViewModel.kt:860)
>         at com.arandusoft.posberry.ventastablet.CobrarActivity$prepararVenta$1.invokeSuspend(CobrarActivity.kt:287)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Comment by lbrasseur** [comment]
Hice unos ajustes en el branch [feature/issue_8](https://github.com/NibiruOS/afip/tree/feature/issue_8). Pueden probar si con estos cambios el error deja de ocurrir?

Pueden ver los cambios en este [Pull Request](https://github.com/NibiruOS/afip/pull/9)

Gracias!!

**Comment by lbrasseur** [comment]
Dicho sea de paso, Android con Kotlin, cool :)

**Comment by lainz** [comment]
Hola, gracias, hay un tema es que necesitamos usar dos fixes, el de BaseSetupDao public y este otro, hay forma de poder usar los dos?

https://github.com/NibiruOS/afip/pull/6

**Comment by lbrasseur** [comment]
Ah, no sabía que el otro fix había funcionado. Megeemoslos en el branch develop a ambos y probamos. Te acordas cual branch era?

**Comment by lainz** [comment]
En un fork que hice yo. Si funciona bien
 Esta en el pull request.

**Comment by lbrasseur** [comment]
Listo, ya mergee ambas ramas en `develop`. Pueden probar con esa versión? Gracias!!

**Comment by lainz** [comment]
Hola, ok gracias, ahora lo voy a probar.

**Comment by lainz** [comment]
Anda perfecto, funciona con los dos tipos de key.

**Comment by lbrasseur** [comment]
Una maravilla. Cuando tenga un rato, lo mergeo en master y publico a maven. Voy a correr los tests antes.

**Comment by lainz** [comment]
Muchisimas gracias por tu ayuda y por el componente de AFIP, es realmente muy util y nos ahorró mucho tiempo.

**Comment by lbrasseur** [comment]
De nada, gracias a ustedes !
